openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of users with details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    gender:
                      type: string
              example:
                - name: aaa
                  age: 1
                  gender: male
                - name: bbb
                  age: 2
                  gender: male
                - name: ccc
                  age: 3
                  gender: male
